<?php
$esEstudiante=ControladorPermisos::esEstudiante(); $esDocente=ControladorPermisos::esDocente();
$idUsuario=(int)($_SESSION['usuario']['id']??0); $idEstudiante=$esEstudiante?ControladorPermisos::idEstudianteContexto():0; $idDocente=$esDocente?$idUsuario:0;
$vistasPermitidas=$esEstudiante?['estudiante']:($esDocente?['materia','estudiante','detalle']:['resumen','materia','estudiante','detalle']);
$vista=trim((string)($_GET['vista']??($esEstudiante?'estudiante':($esDocente?'materia':'resumen')))); if(!in_array($vista,$vistasPermitidas,true)){$vista=$vistasPermitidas[0];}
$calificaciones=ControladorCalificaciones::crtCalificacionesGenerales($idEstudiante,$idDocente);
$cierres=ControladorCalificaciones::crtResumenCierresGenerales($idEstudiante,$idDocente);
$secciones=$esEstudiante?[]:ControladorCalificaciones::crtSeccionesParaCalificaciones($idDocente);
$e=static function($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}; $fecha=static function($v){$t=strtotime((string)$v);return $t?date('d/m/Y',$t):'Sin fecha';};
$etiquetas=['resumen'=>'Resumen final','materia'=>'Por materia','estudiante'=>'Por estudiante','detalle'=>'Registro detallado'];
$grupos=[];$periodos=[]; foreach($cierres as $c){$clave=$c['id_estudiante'].'-'.$c['id_seccion'];if(!isset($grupos[$clave])){$grupos[$clave]=['estudiante'=>trim($c['apellidoUsuario'].' '.$c['nombreUsuario']),'curso'=>$c['curso'],'materia'=>$c['materia'],'docente'=>$c['docente'],'notas'=>[]];}$periodos[(int)$c['idPeriodo']]=['nombre'=>$c['periodo'],'orden'=>(int)$c['ordenPeriodo']];$grupos[$clave]['notas'][(int)$c['idPeriodo']]=$c;} uasort($periodos,static function($a,$b){return $a['orden']<=>$b['orden'];});
$estudiantes=[];foreach($calificaciones as $item){$id=(int)($item['id_estudiante']??0);if($id){$estudiantes[$id]=trim(($item['apellidoUsuario']??'').' '.($item['nombreUsuario']??''));}}asort($estudiantes,SORT_NATURAL|SORT_FLAG_CASE);
?>
<section class="content page-fade"><div class="container-fluid">
<div class="entity-hero mb-3"><div class="entity-hero__content"><span class="entity-kicker mb-3"><?php echo $esEstudiante?'Mi seguimiento':'Seguimiento académico';?></span><h1 class="entity-title mb-2">Calificaciones</h1><p class="entity-lead mb-0"><?php echo $esEstudiante?'Tus resultados organizados por materia y período.':'Una vista para cada necesidad: cierre, materia, estudiante o auditoría.';?></p></div></div>
<?php if(!$esEstudiante):?><nav class="grade-view-tabs mb-4" aria-label="Vistas de calificaciones"><?php foreach($vistasPermitidas as $nombre):?><a class="grade-view-tab <?php echo $vista===$nombre?'active':'';?>" href="index.php?r=calificaciones&amp;vista=<?php echo $e($nombre);?>"><i class="fas <?php echo ['resumen'=>'fa-chart-bar','materia'=>'fa-book-open','estudiante'=>'fa-user-graduate','detalle'=>'fa-list'][$nombre];?>"></i><?php echo $e($etiquetas[$nombre]);?></a><?php endforeach;?></nav><?php endif;?>

<?php if($vista==='resumen'):?>
<div class="card glass-card"><div class="card-header section-header-soft d-flex flex-wrap justify-content-between align-items-center"><div><h3 class="card-title mb-1">Resultados de cierre</h3><small class="text-muted">Una fila por estudiante y materia; sin mezclar evaluaciones parciales.</small></div><label class="management-search mb-0"><i class="fas fa-search"></i><input type="search" class="form-control form-control-sm" placeholder="Buscar estudiante, curso o materia..." data-grade-search></label></div><div class="card-body p-0">
<?php if(!$grupos):?><div class="empty-state my-4"><i class="fas fa-flag-checkered"></i><h4>Aún no hay notas de cierre</h4><p>Los resultados aparecerán cuando el docente calcule el cierre de un período.</p></div><?php else:?><div class="table-responsive"><table class="table table-hover grade-summary-table mb-0"><thead><tr><th>Estudiante</th><th>Curso</th><th>Materia</th><th>Profesor</th><?php foreach($periodos as $p):?><th><?php echo $e($p['nombre']);?></th><?php endforeach;?><th>Estado</th></tr></thead><tbody>
<?php foreach($grupos as $g):$ultima=null;foreach($periodos as $idP=>$p){if(isset($g['notas'][$idP])){$ultima=$g['notas'][$idP];}}$notaUltima=$ultima['calificacionCierre']??null;?><tr data-grade-row data-search="<?php echo $e(implode(' ',[$g['estudiante'],$g['curso'],$g['materia'],$g['docente']]));?>"><td><strong><?php echo $e($g['estudiante']);?></strong></td><td><?php echo $e($g['curso']);?></td><td><?php echo $e($g['materia']);?></td><td><?php echo $e($g['docente']);?></td><?php foreach($periodos as $idP=>$p):$n=$g['notas'][$idP]['calificacionCierre']??null;?><td><span class="grade-result <?php echo $n===null?'is-empty':((float)$n>=7?'is-approved':'is-failed');?>"><?php echo $n===null?'—':$e(number_format((float)$n,2));?></span></td><?php endforeach;?><td><?php if($notaUltima===null):?><span class="badge badge-light">Pendiente</span><?php elseif((float)$notaUltima>=7):?><span class="badge badge-success">Aprobado</span><?php else:?><span class="badge badge-danger">Desaprobado</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div></div>

<?php elseif($vista==='materia'):?>
<div class="d-flex flex-wrap justify-content-between align-items-center mb-3"><div><h3 class="mb-1">Materias</h3><p class="text-muted mb-0">Elegí una materia para abrir su planilla completa.</p></div><label class="management-search mb-0"><i class="fas fa-search"></i><input type="search" class="form-control form-control-sm" placeholder="Buscar curso o materia..." data-grade-search></label></div>
<?php if(!$secciones):?><div class="card glass-card"><div class="empty-state my-4"><i class="fas fa-book-open"></i><h4>No hay materias con calificaciones</h4></div></div><?php else:?><div class="row"><?php foreach($secciones as $s):?><div class="col-md-6 col-xl-4 mb-3" data-grade-row data-search="<?php echo $e(implode(' ',[$s['curso'],$s['materia'],$s['docente'],$s['anio']]));?>"><article class="card glass-card grade-subject-card h-100"><div class="card-body"><small class="text-uppercase text-muted"><?php echo $e($s['curso']);?><?php echo $s['anio']?' · '.$e($s['anio']):'';?></small><h4 class="mt-2 mb-1"><?php echo $e($s['materia']);?></h4><p class="text-muted mb-3"><i class="fas fa-chalkboard-teacher mr-1"></i><?php echo $e($s['docente']);?></p><div class="d-flex mb-3"><span class="grade-subject-metric"><strong><?php echo (int)$s['evaluaciones'];?></strong> evaluaciones</span><span class="grade-subject-metric"><strong><?php echo (int)$s['cierres'];?></strong> cierres</span></div><a class="btn btn-primary btn-sm" href="index.php?r=calificaciones-seccion&amp;idSeccion=<?php echo (int)$s['idSeccion'];?>"><i class="fas fa-table mr-1"></i>Abrir planilla</a></div></article></div><?php endforeach;?></div><?php endif;?>

<?php elseif($vista==='estudiante'&&!$esEstudiante):?>
<div class="card glass-card"><div class="card-header section-header-soft"><h3 class="card-title mb-1">Trayectoria de un estudiante</h3><small class="text-muted">Seleccioná un estudiante para ver sus notas como las ve él.</small></div><div class="card-body"><form method="get" class="form-inline"><input type="hidden" name="r" value="calificaciones"><input type="hidden" name="vista" value="estudiante"><select class="form-control mr-2 mb-2" name="idEstudiante" required><option value="">Seleccionar estudiante...</option><?php foreach($estudiantes as $id=>$nombre):?><option value="<?php echo $id;?>" <?php echo (int)($_GET['idEstudiante']??0)===$id?'selected':'';?>><?php echo $e($nombre);?></option><?php endforeach;?></select><button class="btn btn-primary mb-2" type="submit">Ver calificaciones</button></form></div></div>
<?php $consultaId=(int)($_GET['idEstudiante']??0);if(!isset($estudiantes[$consultaId])){$consultaId=0;}if($consultaId>0):$calificaciones=ControladorCalificaciones::crtCalificacionesGenerales($consultaId,0);?><div class="card glass-card mt-3"><div class="card-header section-header-soft"><h3 class="card-title mb-0"><?php echo $e($estudiantes[$consultaId]);?></h3></div><?php include __DIR__.'/calificaciones-lista.inc.php';?></div><?php endif;?>

<?php elseif($vista==='estudiante'):?><div class="card glass-card"><div class="card-header section-header-soft"><h3 class="card-title mb-0">Mis calificaciones</h3></div><?php include __DIR__.'/calificaciones-lista.inc.php';?></div>
<?php else:?><div class="card glass-card"><div class="card-header section-header-soft d-flex flex-wrap justify-content-between align-items-center"><div><h3 class="card-title mb-1">Registro detallado</h3><small class="text-muted">Historial cronológico de actividades, evaluaciones y cierres.</small></div><label class="management-search mb-0"><i class="fas fa-search"></i><input type="search" class="form-control form-control-sm" placeholder="Buscar..." data-grade-search></label></div><?php include __DIR__.'/calificaciones-lista.inc.php';?></div><?php endif;?>
</div></section>
<script>document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('[data-grade-search]').forEach(function(input){input.addEventListener('input',function(){var q=this.value.toLowerCase().trim();document.querySelectorAll('[data-grade-row]').forEach(function(row){row.style.display=((row.getAttribute('data-search')||'').toLowerCase().indexOf(q)!==-1)?'':'none';});});});});</script>
