<?php
require_once('conexion.php');
class ModeloAsistencias
{
    private static $preparada=false;
    public static function prepararTablas(){if(self::$preparada)return;$pdo=Conexion::conectar();$pdo->exec("CREATE TABLE IF NOT EXISTS asistencia_clases(idClase INT NOT NULL AUTO_INCREMENT,id_seccion INT NOT NULL,id_curso INT NOT NULL,fechaClase DATE NOT NULL,tema VARCHAR(180) NULL,creadaPor INT NOT NULL,fechaCreacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(idClase),UNIQUE KEY uq_asistencia_fecha(id_seccion,fechaClase),KEY idx_asistencia_curso(id_curso)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$pdo->exec("CREATE TABLE IF NOT EXISTS asistencia_registros(idAsistencia INT NOT NULL AUTO_INCREMENT,id_clase INT NOT NULL,id_estudiante INT NOT NULL,estado VARCHAR(15) NOT NULL DEFAULT 'PRESENTE',observacion VARCHAR(255) NULL,actualizadoPor INT NULL,fechaActualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(idAsistencia),UNIQUE KEY uq_asistencia_estudiante(id_clase,id_estudiante),KEY idx_asistencia_alumno(id_estudiante)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");self::$preparada=true;}
    public static function mdlSecciones($idDocente=0){self::prepararTablas();$f=(int)$idDocente>0?' WHERE s.docente=:d OR s.tutor=:d OR c.responsable=:d':'';$st=Conexion::conectar()->prepare("SELECT s.idSeccion,s.tituloSeccion materia,c.idCurso,c.nombreCurso curso,CONCAT(u.nombreUsuario,' ',u.apellidoUsuario) docente,COUNT(DISTINCT ac.idClase) clases FROM secciones s INNER JOIN cursos c ON c.idCurso=s.id_curso LEFT JOIN usuarios u ON u.idUsuario=s.docente LEFT JOIN asistencia_clases ac ON ac.id_seccion=s.idSeccion $f GROUP BY s.idSeccion ORDER BY c.nombreCurso,s.tituloSeccion");if((int)$idDocente>0)$st->bindValue(':d',(int)$idDocente,PDO::PARAM_INT);$st->execute();return $st->fetchAll(PDO::FETCH_ASSOC);}
    public static function mdlCrearClase($idSeccion,$idCurso,$fecha,$tema,$idUsuario){self::prepararTablas();$pdo=Conexion::conectar();$st=$pdo->prepare('INSERT INTO asistencia_clases(id_seccion,id_curso,fechaClase,tema,creadaPor) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE tema=VALUES(tema),idClase=LAST_INSERT_ID(idClase)');$st->execute([(int)$idSeccion,(int)$idCurso,$fecha,$tema,(int)$idUsuario]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare("INSERT IGNORE INTO asistencia_registros(id_clase,id_estudiante,estado,actualizadoPor) SELECT ?,a.id_estudiante,'PRESENTE',? FROM asignacioncursos a INNER JOIN usuarios u ON u.idUsuario=a.id_estudiante WHERE a.id_seccion=? AND u.activo=1 AND (a.fechaAlta IS NULL OR DATE(a.fechaAlta)<=?) AND (a.fechaBaja IS NULL OR DATE(a.fechaBaja)>?)");$q->execute([$id,(int)$idUsuario,(int)$idCurso,$fecha,$fecha]);return $id;}
    public static function mdlClasesSeccion($idSeccion){self::prepararTablas();$st=Conexion::conectar()->prepare("SELECT c.*,COUNT(r.idAsistencia) total,SUM(r.estado='PRESENTE') presentes,SUM(r.estado='AUSENTE') ausentes,SUM(r.estado='TARDANZA') tardanzas,SUM(r.estado='JUSTIFICADA') justificadas FROM asistencia_clases c LEFT JOIN asistencia_registros r ON r.id_clase=c.idClase WHERE c.id_seccion=? GROUP BY c.idClase ORDER BY c.fechaClase DESC");$st->execute([(int)$idSeccion]);return $st->fetchAll(PDO::FETCH_ASSOC);}
    public static function mdlClase($idClase){self::prepararTablas();$st=Conexion::conectar()->prepare('SELECT c.*,s.tituloSeccion materia,cu.nombreCurso curso FROM asistencia_clases c INNER JOIN secciones s ON s.idSeccion=c.id_seccion INNER JOIN cursos cu ON cu.idCurso=c.id_curso WHERE c.idClase=?');$st->execute([(int)$idClase]);return $st->fetch(PDO::FETCH_ASSOC)?:null;}
    public static function mdlRegistrosClase($idClase){self::prepararTablas();$st=Conexion::conectar()->prepare('SELECT r.*,u.nombreUsuario,u.apellidoUsuario FROM asistencia_registros r INNER JOIN usuarios u ON u.idUsuario=r.id_estudiante WHERE r.id_clase=? ORDER BY u.apellidoUsuario,u.nombreUsuario');$st->execute([(int)$idClase]);return $st->fetchAll(PDO::FETCH_ASSOC);}
    public static function mdlResumenEstudiantesSeccion($idSeccion){self::prepararTablas();$st=Conexion::conectar()->prepare("SELECT r.id_estudiante,COUNT(*) clases,SUM(r.estado='AUSENTE') ausentes,SUM(r.estado='TARDANZA') tardanzas,SUM(r.estado='JUSTIFICADA') justificadas,ROUND(100*SUM(r.estado IN ('PRESENTE','TARDANZA','JUSTIFICADA'))/COUNT(*),1) porcentaje FROM asistencia_registros r INNER JOIN asistencia_clases c ON c.idClase=r.id_clase WHERE c.id_seccion=? GROUP BY r.id_estudiante");$st->execute([(int)$idSeccion]);return $st->fetchAll(PDO::FETCH_ASSOC);}
    public static function mdlGuardar($idClase,array $estados,array $observaciones,$idUsuario){self::prepararTablas();$permitidos=array_fill_keys(array_map('intval',array_column(self::mdlRegistrosClase($idClase),'id_estudiante')),true);$st=Conexion::conectar()->prepare('UPDATE asistencia_registros SET estado=?,observacion=?,actualizadoPor=?,fechaActualizacion=NOW() WHERE id_clase=? AND id_estudiante=?');foreach($estados as $id=>$estado){$id=(int)$id;$estado=strtoupper((string)$estado);if(!isset($permitidos[$id])||!in_array($estado,['PRESENTE','AUSENTE','TARDANZA','JUSTIFICADA'],true))continue;if(!$st->execute([$estado,trim((string)($observaciones[$id]??'')),(int)$idUsuario,(int)$idClase,$id]))return 'error';}return 'ok';}
    public static function mdlResumenEstudiante($idEstudiante){self::prepararTablas();$st=Conexion::conectar()->prepare("SELECT s.tituloSeccion materia,c.nombreCurso curso,COUNT(*) clases,SUM(r.estado='PRESENTE') presentes,SUM(r.estado='AUSENTE') ausentes,SUM(r.estado='TARDANZA') tardanzas,SUM(r.estado='JUSTIFICADA') justificadas,ROUND(100*SUM(r.estado IN ('PRESENTE','TARDANZA','JUSTIFICADA'))/COUNT(*),1) porcentaje FROM asistencia_registros r INNER JOIN asistencia_clases ac ON ac.idClase=r.id_clase INNER JOIN secciones s ON s.idSeccion=ac.id_seccion INNER JOIN cursos c ON c.idCurso=ac.id_curso WHERE r.id_estudiante=? GROUP BY ac.id_seccion ORDER BY c.nombreCurso,s.tituloSeccion");$st->execute([(int)$idEstudiante]);return $st->fetchAll(PDO::FETCH_ASSOC);}
}
